name: ssh-to-action

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15.2
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.6
      
      - name: Use Node.js 14.15.3
        uses: actions/setup-node@v2
        with:
          node-version: 14.15.3

      - name: SSH connection to Actions
        uses: 1orz/ssh-action@master

      - name: Upload Flies
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Files
          path: upload/
